"""uuid primary keys

Revision ID: 97a0c76500ed
Revises: 
Create Date: 2026-08-05 15:30:05.030373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '97a0c76500ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('companies',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_companies_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_user_id'), 'companies', ['user_id'], unique=False)
    op.create_table('cover_letters',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cover_letters_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cover_letters'))
    )
    op.create_index(op.f('ix_cover_letters_user_id'), 'cover_letters', ['user_id'], unique=False)
    op.create_table('resumes',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_resumes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resumes'))
    )
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_table('job_opportunities',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('application_link', sa.String(length=500), nullable=True),
    sa.Column('salary_range', sa.String(length=100), nullable=True),
    sa.Column('required_skills', sa.JSON(), nullable=True),
    sa.Column('experience_level', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('SAVED', 'APPLIED', 'INTERVIEWING', 'OFFERED', 'REJECTED', 'ARCHIVED', name='opportunitystatus', native_enum=False, length=30), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_job_opportunities_company_id_companies')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_job_opportunities_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_opportunities'))
    )
    op.create_index(op.f('ix_job_opportunities_company_id'), 'job_opportunities', ['company_id'], unique=False)
    op.create_index(op.f('ix_job_opportunities_status'), 'job_opportunities', ['status'], unique=False)
    op.create_index(op.f('ix_job_opportunities_title'), 'job_opportunities', ['title'], unique=False)
    op.create_index(op.f('ix_job_opportunities_user_id'), 'job_opportunities', ['user_id'], unique=False)
    op.create_table('applications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=True),
    sa.Column('cover_letter_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('APPLIED', 'SCREENING', 'INTERVIEW_SCHEDULED', 'INTERVIEW_COMPLETED', 'OFFER', 'REJECTED', 'WITHDRAWN', name='applicationstatus', native_enum=False, length=30), nullable=False),
    sa.Column('applied_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cover_letter_id'], ['cover_letters.id'], name=op.f('fk_applications_cover_letter_id_cover_letters')),
    sa.ForeignKeyConstraint(['opportunity_id'], ['job_opportunities.id'], name=op.f('fk_applications_opportunity_id_job_opportunities')),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_applications_resume_id_resumes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_applications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications')),
    sa.UniqueConstraint('user_id', 'opportunity_id', name='uq_applications_user_opportunity')
    )
    op.create_index(op.f('ix_applications_opportunity_id'), 'applications', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_table('application_status_history',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('APPLIED', 'SCREENING', 'INTERVIEW_SCHEDULED', 'INTERVIEW_COMPLETED', 'OFFER', 'REJECTED', 'WITHDRAWN', name='applicationstatus', native_enum=False, length=30), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_status_history_application_id_applications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_status_history'))
    )
    op.create_index(op.f('ix_application_status_history_application_id'), 'application_status_history', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_status_history_changed_at'), 'application_status_history', ['changed_at'], unique=False)
    op.create_table('follow_ups',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'DONE', 'SKIPPED', name='followupstatus', native_enum=False, length=30), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_follow_ups_application_id_applications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_follow_ups'))
    )
    op.create_index(op.f('ix_follow_ups_application_id'), 'follow_ups', ['application_id'], unique=False)
    op.create_index(op.f('ix_follow_ups_scheduled_at'), 'follow_ups', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_follow_ups_status'), 'follow_ups', ['status'], unique=False)
    op.create_table('interviews',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('PHONE', 'VIDEO', 'TECHNICAL', 'PANEL', 'ONSITE', 'OTHER', name='interviewtype', native_enum=False, length=30), nullable=False),
    sa.Column('location_or_link', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='interviewstatus', native_enum=False, length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_interviews_application_id_applications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interviews'))
    )
    op.create_index(op.f('ix_interviews_application_id'), 'interviews', ['application_id'], unique=False)
    op.create_index(op.f('ix_interviews_scheduled_at'), 'interviews', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_interviews_status'), 'interviews', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interviews_status'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_scheduled_at'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_application_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_follow_ups_status'), table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_scheduled_at'), table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_application_id'), table_name='follow_ups')
    op.drop_table('follow_ups')
    op.drop_index(op.f('ix_application_status_history_changed_at'), table_name='application_status_history')
    op.drop_index(op.f('ix_application_status_history_application_id'), table_name='application_status_history')
    op.drop_table('application_status_history')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_opportunity_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_job_opportunities_user_id'), table_name='job_opportunities')
    op.drop_index(op.f('ix_job_opportunities_title'), table_name='job_opportunities')
    op.drop_index(op.f('ix_job_opportunities_status'), table_name='job_opportunities')
    op.drop_index(op.f('ix_job_opportunities_company_id'), table_name='job_opportunities')
    op.drop_table('job_opportunities')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_cover_letters_user_id'), table_name='cover_letters')
    op.drop_table('cover_letters')
    op.drop_index(op.f('ix_companies_user_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
